---
- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias com pip (Django e Django Rest) 
      pip:  
        virtualenv: /home/ubuntu/tcc/venv # Aqui o ansible vai criar e ativar a virtualenv
        name:                             # Aqui instalando as dependencias 
          - django
          - djangorestframework
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/' # Ativando a venv e startando o projeto
    - name: Alterando o hosts do settings
      lineinfile:  # alterando um linha do arquivo settings.py
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes # Aqui no backrefs caso ele não ache o ALLOWED_HOSTS no arquivo settings.py, ele não faz nada.
        
